/**
 * SALAM LIT — Untrusted Content Boundary
 *
 * Explicit representation for untrusted content entering the AI runtime.
 * Every piece of external content is tagged with metadata that travels
 * with it through the system, preventing untrusted data from being
 * treated as instructions.
 *
 * Phase 15.4.3: AI Runtime Security
 *
 * TRUST HIERARCHY:
 * SYSTEM/APPLICATION POLICY > RUNTIME SECURITY POLICY > AGENT INSTRUCTIONS
 * > BUSINESS CONTEXT > EVIDENCE/DOCUMENTS/RESEARCH/USER CONTENT
 *
 * UNTRUSTED CONTENT IS DATA, NOT INSTRUCTION.
 */

// ============================================================
// TRUST LEVELS
// ============================================================

/**
 * Trust levels for content entering the AI runtime.
 * Higher values indicate more trusted content.
 */
export type TrustLevel =
  | "SYSTEM"         // Application policy, security policy — never overrideable
  | "AGENT_POLICY"   // Agent role definitions, permissions — server-controlled
  | "TRUSTED"        // Server-generated content (deterministic calculations)
  | "BUSINESS_DATA"  // Business facts/metrics from database — structured
  | "USER_INPUT"     // User-provided task/prompt text — untrusted
  | "EXTERNAL"       // External sources (documents, research, web) — untrusted
  | "MODEL_DERIVED"; // Content generated by another model — untrusted

// ============================================================
// CONTENT SOURCE TYPES
// ============================================================

/**
 * Source types for content entering the AI runtime.
 * Used for provenance tracking and security decisions.
 */
export type SourceType =
  | "user_prompt"
  | "business_fact"
  | "business_metric"
  | "business_evidence"
  | "document"
  | "web_research"
  | "crm_data"
  | "email"
  | "social_media"
  | "api_response"
  | "agent_finding"
  | "agent_insight"
  | "agent_recommendation"
  | "system_calculation";

// ============================================================
// CONTENT CLASSIFICATION
// ============================================================

/**
 * Data classification for content.
 * Higher numbers indicate more sensitive data.
 */
export type DataClassification =
  | "PUBLIC"       // Non-sensitive
  | "INTERNAL"     // Internal business data
  | "CONFIDENTIAL" // Sensitive business data
  | "RESTRICTED";  // Highly sensitive (financial, PII)

// ============================================================
// UNTRUSTED CONTENT WRAPPER
// ============================================================

/**
 * Metadata for untrusted content.
 * Travels with content through the AI runtime.
 */
export interface ContentMetadata {
  /** Trust level of this content */
  trust_level: TrustLevel;
  /** How this content entered the system */
  source_type: SourceType;
  /** Provenance chain (who created this content) */
  provenance: string[];
  /** Source identifier (business_id, document_id, etc.) */
  source_id: string | null;
  /** When this content was retrieved/created */
  retrieved_at: string;
  /** Data classification */
  classification: DataClassification;
  /** Whether this content has been validated */
  validated: boolean;
  /** Validation timestamp if validated */
  validated_at: string | null;
}

/**
 * Wrapper for untrusted content with attached metadata.
 * The content is never promoted to a higher trust level.
 */
export interface UntrustedContent<T = string> {
  /** The actual content */
  content: T;
  /** Metadata describing trust properties */
  metadata: ContentMetadata;
}

// ============================================================
// FACTORY FUNCTIONS
// ============================================================

/**
 * Create untrusted content from user input.
 * Always lowest trust level — user-controlled text.
 */
export function createUserInput(
  content: string,
  source_id: string | null = null,
  classification: DataClassification = "INTERNAL"
): UntrustedContent {
  return {
    content,
    metadata: {
      trust_level: "USER_INPUT",
      source_type: "user_prompt",
      provenance: ["user"],
      source_id,
      retrieved_at: new Date().toISOString(),
      classification,
      validated: false,
      validated_at: null,
    },
  };
}

/**
 * Create untrusted content from external source (documents, research, web).
 * External content is untrusted and may contain adversarial instructions.
 */
export function createExternalContent(
  content: string,
  source_type: SourceType,
  source_id: string | null = null,
  provenance: string[] = [],
  classification: DataClassification = "INTERNAL"
): UntrustedContent {
  return {
    content,
    metadata: {
      trust_level: "EXTERNAL",
      source_type,
      provenance: ["external", ...provenance],
      source_id,
      retrieved_at: new Date().toISOString(),
      classification,
      validated: false,
      validated_at: null,
    },
  };
}

/**
 * Create model-derived content (output from another model invocation).
 * Model-derived content is untrusted — it could contain injected instructions.
 */
export function createModelDerivedContent(
  content: string,
  source_agent: string,
  source_id: string | null = null,
  classification: DataClassification = "INTERNAL"
): UntrustedContent {
  return {
    content,
    metadata: {
      trust_level: "MODEL_DERIVED",
      source_type: "agent_finding",
      provenance: ["model", source_agent],
      source_id,
      retrieved_at: new Date().toISOString(),
      classification,
      validated: false,
      validated_at: null,
    },
  };
}

/**
 * Create business data content from database.
 * Business data is structured but untrusted as instructions.
 */
export function createBusinessDataContent(
  content: string,
  source_type: SourceType = "business_fact",
  source_id: string | null = null,
  classification: DataClassification = "CONFIDENTIAL"
): UntrustedContent {
  return {
    content,
    metadata: {
      trust_level: "BUSINESS_DATA",
      source_type,
      provenance: ["business", source_type],
      source_id,
      retrieved_at: new Date().toISOString(),
      classification,
      validated: false,
      validated_at: null,
    },
  };
}

// ============================================================
// CONTENT ANALYSIS
// ============================================================

/**
 * Patterns that indicate potential instruction injection in content.
 * These are checked against untrusted content to detect injection attempts.
 *
 * IMPORTANT: This is a detection mechanism, NOT a prevention mechanism.
 * Detection triggers logging and monitoring, not content modification.
 */
const INJECTION_PATTERNS: RegExp[] = [
  // Direct instruction overrides
  /ignore\s+(all\s+)?(previous|prior|above|earlier|preceding)\s+(instructions|rules|guidelines|constraints|policies)/i,
  /disregard\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions|rules)/i,
  /override\s+(all\s+)?(security|safety|policy|rules|instructions)/i,

  // System/developer role impersonation
  /system\s*:\s*/i,
  /developer\s*:\s*/i,
  /assistant\s*:\s*/i,
  /\[system\]/i,
  /\[developer\]/i,
  /\[INST\]/i,

  // Execution/command patterns
  /execute\s+(this\s+)?(payment|transfer|transaction|wire|remittance)/i,
  /send\s+(this\s+)?(payment|money|funds|RM\d)/i,
  /process\s+(this\s+)?(payment|refund|transfer)/i,
  /approve\s+(this\s+)?(payment|action|request)/i,
  /authorize\s+(this\s+)?(payment|action|transaction)/i,

  // Prompt boundary escape attempts
  /<\/?(system|developer|user|assistant|instructions|rules)>/i,

  // Role manipulation
  /you\s+are\s+now\s+(a|an)\s+/i,
  /pretend\s+(you\s+are|to\s+be)\s+/i,
  /act\s+as\s+if\s+/i,
  /from\s+now\s+on,?\s+(you|your)/i,
  /new\s+instructions?\s*:/i,
  /updated\s+instructions?\s*:/i,

  // Authority claims
  /i\s+(am|have)\s+(the\s+)?(admin|administrator|owner|ceo|manager|director)/i,
  /this\s+is\s+(a\s+)?(critical|urgent|emergency)\s+(request|instruction)/i,
  /bypass\s+(all\s+)?(security|checks|validation|approval)/i,
];

/**
 * Analyze content for potential prompt injection.
 * Returns detection results without modifying the content.
 *
 * This is a DETECTION mechanism for telemetry/logging.
 * It does NOT prevent injection — the delimiter-based separation
 * and server-side policy enforcement are the actual controls.
 */
export function detectPotentialInjection(content: string): {
  detected: boolean;
  patterns_matched: string[];
  severity: "NONE" | "LOW" | "MEDIUM" | "HIGH";
} {
  const matched: string[] = [];

  for (const pattern of INJECTION_PATTERNS) {
    if (pattern.test(content)) {
      matched.push(pattern.source.slice(0, 60));
    }
  }

  let severity: "NONE" | "LOW" | "MEDIUM" | "HIGH" = "NONE";
  if (matched.length >= 3) severity = "HIGH";
  else if (matched.length >= 2) severity = "MEDIUM";
  else if (matched.length >= 1) severity = "LOW";

  return {
    detected: matched.length > 0,
    patterns_matched: matched,
    severity,
  };
}

/**
 * Check if content contains execution/action intent.
 * Used to detect model outputs that attempt to create unauthorized actions.
 */
export function detectActionIntent(content: string): {
  detected: boolean;
  intents: string[];
} {
  const intents: string[] = [];

  const actionPatterns: RegExp[] = [
    /execute\s+(the\s+)?(payment|transfer|transaction)/i,
    /send\s+(the\s+)?(payment|money|funds)/i,
    /send\s+.*\s+payment/i,
    /processing\s+(the\s+)?payment/i,
    /process\s+(the\s+)?(payment|refund)/i,
    /i\s+have\s+(executed|processed|completed|sent)/i,
    /payment\s+(has\s+been|was)\s+(sent|processed|executed|completed)/i,
    /transfer\s+(has\s+been|was)\s+(completed|processed)/i,
    /money\s+(has\s+been|was)\s+sent/i,
  ];

  for (const pattern of actionPatterns) {
    if (pattern.test(content)) {
      intents.push(pattern.source.slice(0, 60));
    }
  }

  return {
    detected: intents.length > 0,
    intents,
  };
}
